# Generated by Django 5.1.4 on 2024-12-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="images/")),
                ("address", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=1000000)),
            ],
        ),
    ]
