# Generated by Django 5.1.4 on 2024-12-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grid",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
